import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import Hero from '@/components/hero/Hero'
import About from '@/components/about/About'
import Experience from '@/components/experience/Experience'
import Contact from '@/components/contact/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>fullstackstef</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Hero />
        <About />
        <Experience />
        <Contact />
      </div>
    </>
  )
}
